"use strict";
exports.__esModule = true;
require("reflect-metadata");
var inversify_1 = require("inversify");
var discord_js_1 = require("discord.js");
var types_1 = require("./src/types");
var bot_1 = require("./src/bot");
exports.container = new inversify_1.Container();
exports.container.bind(types_1.TYPES.Bot).to(bot_1.Bot).inSingletonScope();
exports.container.bind(types_1.TYPES.Client).toConstantValue(new discord_js_1.Client());
exports.container.bind(types_1.TYPES.Token).toConstantValue(process.env.TOKEN);
exports["default"] = exports.container;
